# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  web:
    image: ghcr.io/canastawiki/canasta@sha256:cd7dda14596a68cdb2b659398c18cc892535d6475f9a81d77690abcf02571ab9
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - db
    extra_hosts:
      - "gateway.docker.internal:host-gateway"
    depends_on:
      - db
    environment:
      # Sourced from .env
      - MW_SITE_SERVER=${MW_SITE_SERVER:-http://localhost}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-12M}
      - PHP_POST_MAX_SIZE=${PHP_UPLOAD_MAX_FILESIZE:-12M}
      - PHP_MAX_INPUT_VARS=${PHP_MAX_INPUT_VARS:-1000}
      - MW_SITEMAP_SUBDIR
      - MW_SITEMAP_IDENTIFIER
    volumes:
      - type: bind
        source: ./mountedResources
        target: /var/www/mediawiki/w/resources/mounted
      - ./extensions:/var/www/mediawiki/w/user-extensions
      - ./skins:/var/www/mediawiki/w/user-skins
      - ./config:/mediawiki/config
      - ./images:/mediawiki/images
  db:
    image: mysql:8.1
    restart: always
    expose:
      - 3306 
    environment:
      MYSQL_DATABASE: ko-lab_wiki 
      MYSQL_USER: admin 
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: 'no'
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/mysql
